/* Generated by automated build script */
#define SNAPSHOT
#define TEXTVER "Development snapshot 2018-06-17.20e8fde"
#define SSHVER "PuTTY-Snapshot-2018-06-17.20e8fde"
#define BINARY_VERSION 0,70,1348,0
#define SOURCE_COMMIT "20e8fdece39dd1d680c0feb8eb1432e18c81ade2"
